version: 2
jobs:
  build:
    working_directory: ~/circle-ci-test # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:lts # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: npm-update
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: node-get-version
          command: node -v
      - run:
          name: npm-get-version
          command: npm -v
      - run:
          name: npm-install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: run-lint-and-tests
          command: npm run check
      - store_artifacts:
          path: coverage
#      - run: # run coverage report
#          name: code-coverage
#          command: './node_modules/.bin/nyc report --reporter=text-lcov'
#      - store_artifacts: # special step to save test results as as artifact
#          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
#          path: test-results.xml
#          prefix: tests
#      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
#          path: coverage
#          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-report.xml
#      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
